In [ ]:
# Package Imports

import pandas as pd
import matplotlib.pyplot as plt

# Data Examination

The first step of course is to read and examine the data:

In [2]:
df = pd.read_csv("../data/PRSA_data.csv")
df.head()

   No  year  month  day  hour  pm2.5  DEWP  TEMP    PRES cbwd    Iws  Is  Ir
0   1  2010      1    1     0    NaN   -21 -11.0  1021.0   NW   1.79   0   0
1   2  2010      1    1     1    NaN   -21 -12.0  1020.0   NW   4.92   0   0
2   3  2010      1    1     2    NaN   -21 -11.0  1019.0   NW   6.71   0   0
3   4  2010      1    1     3    NaN   -21 -14.0  1019.0   NW   9.84   0   0
4   5  2010      1    1     4    NaN   -20 -12.0  1018.0   NW  12.97   0   0

Nothing stands out immediately - we check for missing values:

In [13]:
df.info()
df.isna().sum()

<class 'pandas.DataFrame'>
RangeIndex: 43824 entries, 0 to 43823
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   No      43824 non-null  int64
 1   year    43824 non-null  int64
 2   month   43824 non-null  int64
 3   day     43824 non-null  int64
 4   hour    43824 non-null  int64
 5   pm2.5   41757 non-null  float64
 6   DEWP    43824 non-null  int64
 7   TEMP    43824 non-null  float64
 8   PRES    43824 non-null  float64
 9   cbwd    43824 non-null  str
 10  Iws     43824 non-null  float64
 11  Is      43824 non-null  int64
 12  Ir      43824 non-null  int64
dtypes: float64(4), int64(8), str(1)
memory usage: 4.3 MB

No          0
year        0
month       0
day         0
hour        0
pm2.5    2067
DEWP        0
TEMP        0
PRES        0
cbwd        0
Iws         0
Is          0
Ir          0
dtype: int64

We see that there are 2,067 missing values in the `pm2.5` column, which is the target variable. We will investigate this further. Next, we get an idea of the distribution of some of the variables:

In [14]:
df.describe()

,No,year,month,day,hour,pm2.5,DEWP,TEMP,PRES,Iws,Is,Ir
count,43824.000000,43824.000000,43824.000000,43824.000000,43824.000000,41757.000000,43824.000000,43824.000000,43824.000000,43824.000000,43824.000000,43824.000000
mean,21912.500000,2012.000000,6.523549,15.727820,11.500000,98.613215,1.817246,12.448521,1016.447654,23.889140,0.052734,0.194916
std,12651.043435,1.413842,3.448572,8.799425,6.922266,92.050387,14.433440,12.198613,10.268698,50.010635,0.760375,1.415867
min,1.000000,2010.000000,1.000000,1.000000,0.000000,0.000000,-40.000000,-19.000000,991.000000,0.450000,0.000000,0.000000
25%,10956.750000,2011.000000,4.000000,8.000000,5.750000,29.000000,-10.000000,2.000000,1008.000000,1.790000,0.000000,0.000000
50%,21912.500000,2012.000000,7.000000,16.000000,11.500000,72.000000,2.000000,14.000000,1016.000000,5.370000,0.000000,0.000000
75%,32868.250000,2013.000000,10.000000,23.000000,17.250000,137.000000,15.000000,23.000000,1025.000000,21.910000,0.000000,0.000000
max,43824.000000,2014.000000,12.000000,31.000000,23.000000,994.000000,28.000000,42.000000,1046.000000,585.600000,27.000000,36.000000

The target variable `pm2.5` is clearly right-skewed. The mean is about 98.6, which sits far above the median value of 72. Further, the max value of 994 is about 7 times the 75th percentile value of 137. This suggests the pollution for most hours is typical, with some being extremely high. It is worth considering a log transform on the variable to see if it yields a more symmetric distribution.

Similar behavior applies to the `Iws` column (cumulated wind speed). The mean is about 24, median is about 5.37, and max is about 585.6. These are running totals, so periods of persistent high wind likely drive this distribution. This is important to consider when choosing features for models; interpreting these values as instantaneous rates would be incorrect.

`Is` and `Ir` are a little different; as seen in `df.describe()`, at least 75% of the rows are zero. This implies that most hours, it is not raining or snowing, which is reasonable to expect. Log transforms will not fix the pile of zeros, and instead we will consider including these as "Is there precipitation?" columns or if they can be left as is.